apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demoapp
spec:
  host: {{ .Values.route.host | default "paul.apps-crc.testing" }}
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: demoapp
    weight: 100
  wildcardPolicy: None
