apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: art-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/overlays/dev
    repoURL: https://gitea.apps.cluster-vswgc.sandbox1219.opentlc.com/user1/demo-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
